server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tourplanner}
    username: ${DB_USER:tourplanner}
    password: ${DB_PASSWORD:tourplanner}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

app:
  open-route-service:
    api-key: ${ORS_API_KEY}
    base-url: ${ORS_BASE_URL:https://api.openrouteservice.org}
  open-weather:
    api-key: ${OPENWEATHER_API_KEY}
    base-url: ${OPENWEATHER_BASE_URL:https://api.openweathermap.org}

logging:
  level:
    at.fhtw.tourplanner: INFO
